export PATH="$PATH:$HOME/.composer/vendor/bin"
[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
alias vimalas='vim ~/.bashrc'
alias cplc='echo $(history -p !!) | pbcopy'
alias cplout='echo "$(!!)" | pbcopy'
alias dkapp='docker-compose exec app bash'
alias gitdf='git diff'
alias gitdfs='git diff --staged'
alias gitst='git status'
alias gitsts='git status --staged'
alias gitlogo='git log --oneline'
alias gitamd='git commit --amend -m'
alias gitc='git commit'
alias gita='git add'
alias gitp='git push'
